Импорты и настройки

In [1]:
import requests
import pandas as pd
import numpy as np
import csv
import io
import matplotlib.pyplot as plt
import time
import inspect
from kzt_exchangerates import Rates

%matplotlib inline

In [2]:
pd.set_option('display.max_columns', 50)
np.seterr(divide='ignore', invalid='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

Tez bol

In [3]:
# data

Organic = [0, 0, 0] # budget, views, clicks
googleadwords_int = [1680, 646000, 14500]  
Facebook_Ads = [100, 6000, 1000]


bvc = [Organic, googleadwords_int, Facebook_Ads]  

from_date = '2022-11-22'
to_date = '2022-11-30'



# TEZ BOL
app_id = 'com.tezbol.android'  # Tez bol android
token = 'Bearer eyJhbGciOiJBMjU2S1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwidHlwIjoiSldUIiwiemlwIjoiREVGIn0.sEVLFBUJYOA0mqDnHXn26LmhHkk9brtcqEFUQ3ff28aHsMYW4IgcRQ.rHov5TPYLC05J7FU.kPdQbwAy_6DjqVQnHgOVPNh1hLwtSdKrSPIfwVBQx22brT5CfR0-QMnh_Gmz8zFvyKOYXY2JaIfKetASeZ2FM-6VxT8b7MmFESD-McDxnSa6x_HpAbAXT2D2oqK_x7uh7WWF4eVYQTgo6M5UL8qZyg_nBH1FC3BKUxo0NEnUWtdkxlk71GbcGtP7a0Ik1NNgh7f-uFfuDbh9Kx-RhV7m5Io14MuKoh9KW1SAo__N0g2yOk5_1KDgVhGSTPtyiI34FA1O-GB569ufliR4Yo2-i9mLoCWaiJHLltxE55rp39rqLgGQiSxBpAiG-c3gHB5n8cU9pqN4cvRpMMjOTxaAE6FZYM7WlTAx80Pmqy6yVXe3dBBH9UZjpFhc5aR84y-BYU0UnrODff2KT-EjTXap2nWI0ALZCC0LvX57FZk8ZQrlV1UG6tmx2_mXgQNkAuCYNzsgRajRUf3TjLNMEwVTpn-yCYbVo9YtKumwXu9bI-iHIKqPmvr8y466bA5_zYP7MQLG75jnKWbSr3VAf87VNA.VaZ4bKqcqdREmfgWC7bBDg'

Creditomat.MD

In [4]:
# # CREDITOMAT.MD 

# app_id = 'com.kreditomatmd.dozp.ref'   # MD kreditomat android

# token = 'Bearer eyJhbGciOiJBMjU2S1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwidHlwIjoiSldUIiwiemlwIjoiREVGIn0.Hioi6Lb0C7wwtN6_9zoigB37ukPBlJdyF5R7G3DIncShFJtPNs9h9g.eqnAjdwd28XULE_-.IZsJsJuR5e-yVrcmWoDVe-DVURRjFEsQShgWwJ9unBkxAjz72n2IBrWecP7_pA9k6mV7br73JxgvWmPB6RNwTPcPOz0FbBQQIwX-xu2iD3udokHVk3XT5aP_aMHSWkADoeyJZyImnPf10-wCi8-nJ3vivzebPl6VCi5QQ-HorU5O8PLUq9LddE-0L7gfT6S0diMY7yW1HpAGHKethpI7abCwV9_yX88tptFHlaWV8zqsHysoqZmA-6tiyloCIoGOibFgk6Ix5tJYQaZkUFbvQf5IVdwoJVe-VeGEESnBedQA3UBbpAhHB1Hp1OZeZOBUpAOQHQRZkqNvy8y9QMMkr-5-_CS567ZAtUfh3ZbMcHau63e6fsQbbWQhDWeBZ6GDm5OuAIgyyJipAyEf7_6ozL0DS00wUYrhKH1vCF4kMid7VljHcVk2s_-2u79I2ttDsQtK3DGnbSYgsGkktkQDSKGCOlRLNNkpCnHp5bnhmLEbs-BpxwIlHW7PoNi3YQriaBLJrWt1Sn-T3j8N6lIwgFDG0A.sma12W1tpVnUAojhCVLMUA'

# from_date = '2022-09-22'
# to_date = '2022-11-21'

# # media_source = 'Social_instagram'
# # media_source = 'app_land'

# media_source = ['Organic', 'Social_instagram']

Kreditomat.KZ

In [5]:
## KREDITOMAT.KZ

# # app_id = 'id1392973739'   # kreditomat ios
# app_id = 'com.payday.dozp.ref'   # kreditomat android

# token = 'Bearer eyJhbGciOiJBMjU2S1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwidHlwIjoiSldUIiwiemlwIjoiREVGIn0.sEVLFBUJYOA0mqDnHXn26LmhHkk9brtcqEFUQ3ff28aHsMYW4IgcRQ.rHov5TPYLC05J7FU.kPdQbwAy_6DjqVQnHgOVPNh1hLwtSdKrSPIfwVBQx22brT5CfR0-QMnh_Gmz8zFvyKOYXY2JaIfKetASeZ2FM-6VxT8b7MmFESD-McDxnSa6x_HpAbAXT2D2oqK_x7uh7WWF4eVYQTgo6M5UL8qZyg_nBH1FC3BKUxo0NEnUWtdkxlk71GbcGtP7a0Ik1NNgh7f-uFfuDbh9Kx-RhV7m5Io14MuKoh9KW1SAo__N0g2yOk5_1KDgVhGSTPtyiI34FA1O-GB569ufliR4Yo2-i9mLoCWaiJHLltxE55rp39rqLgGQiSxBpAiG-c3gHB5n8cU9pqN4cvRpMMjOTxaAE6FZYM7WlTAx80Pmqy6yVXe3dBBH9UZjpFhc5aR84y-BYU0UnrODff2KT-EjTXap2nWI0ALZCC0LvX57FZk8ZQrlV1UG6tmx2_mXgQNkAuCYNzsgRajRUf3TjLNMEwVTpn-yCYbVo9YtKumwXu9bI-iHIKqPmvr8y466bA5_zYP7MQLG75jnKWbSr3VAf87VNA.VaZ4bKqcqdREmfgWC7bBDg'   

# from_date = '2022-09-22'
# to_date = '2022-11-21'

# # media_source = 'land_calcul'
# # media_source = 'yandexdirect_int'
# media_source = ['calcul_store', 'app_land']

Получаем имена переменных для запроса

In [6]:
''' получаем имена переменных '''

def retrieve_name(var):
        for fi in reversed(inspect.stack()):
            names = [var_name for var_name, var_val in fi.frame.f_locals.items() if var_val is var]
            if len(names) > 0:
                return names[0]
            
media_source = [retrieve_name(x) for x in bvc]

media_source

['Organic', 'googleadwords_int', 'Facebook_Ads']

Функция обращения в AppsFlyer

In [7]:

def pull_request(med_sour):
    
    if med_sour == 'Facebook_Ads':
        url = f"https://hq1.appsflyer.com/api/agg-data/export/app/{app_id}/partners_report/v5?from={from_date}&to={to_date}&media_source={med_sour}&category=facebook"
    else:
        url = f"https://hq1.appsflyer.com/api/agg-data/export/app/{app_id}/partners_report/v5?from={from_date}&to={to_date}&media_source={med_sour}&category=standard"

    headers = {
        "accept": "text/csv",
        "authorization": token
    }


    urlData = requests.get(url, headers=headers).content
    rawData = pd.read_csv(io.StringIO(urlData.decode('utf-8')))
    return rawData

Запрос в Appsflyer

In [8]:
df_agre = None
if type(media_source) == list:
    for i in range(len(media_source)):
        if str(type(df_agre)) == "<class 'NoneType'>":
            df_agre = pull_request(media_source[i])
        else: 
            time.sleep(60)
            df_agre = pd.concat([df_agre, pull_request(media_source[i])])     
else:
    print(15)
    
df_agre

,Agency/PMD (af_prt),Media Source (pid),Campaign (c),Impressions,Clicks,CTR,Installs,Conversion Rate,Sessions,Loyal Users,Loyal Users/Installs,Total Revenue,Total Cost,ROI,ARPU,Average eCPI,af_complete_registration (Unique users),af_complete_registration (Event counter),af_complete_registration (Sales in USD),af_login (Unique users),af_login (Event counter),af_login (Sales in USD),contract_signed (Unique users),contract_signed (Event counter),contract_signed (Sales in USD),...,install_kreditomat (Sales in USD),loan_accepted (Unique users),loan_accepted (Event counter),loan_accepted (Sales in USD),loan_accepted_new (Unique users),loan_accepted_new (Event counter),loan_accepted_new (Sales in USD),loan_rejected (Unique users),loan_rejected (Event counter),loan_rejected (Sales in USD),loan_request (Unique users),loan_request (Event counter),loan_request (Sales in USD),loan_request_new (Unique users),loan_request_new (Event counter),loan_request_new (Sales in USD),submit_loan_application (Unique users),submit_loan_application (Event counter),submit_loan_application (Sales in USD),Campaign Name,Campaign Id,Adset Name,Adset Id,Adgroup Name,Adgroup Id
0,None,Organic,None,NaN,NaN,NaN,4595,NaN,0,3764,0.8192,0.0,NaN,NaN,0.0,NaN,2252,2689,0.0,4186,33439,0.0,0.0,1.0,0.0,...,0.0,418.0,827.0,0.0,0.0,2.0,0.0,2440,10757,0.0,0.0,3.0,0.0,0.0,3.0,0.0,2868,13627,0.0,NaN,NaN,NaN,NaN,NaN,NaN
0,None,googleadwords_int,19012106832,NaN,NaN,NaN,5,NaN,23,4,0.8000,0.0,NaN,NaN,0.0,NaN,3,3,0.0,4,16,0.0,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,2,8,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2,8,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,None,googleadwords_int,19012163952,NaN,NaN,NaN,2,NaN,9,2,1.0000,0.0,NaN,NaN,0.0,NaN,1,1,0.0,1,3,0.0,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,1,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,None,googleadwords_int,19062392763,NaN,NaN,NaN,1,NaN,5,1,1.0000,0.0,NaN,NaN,0.0,NaN,1,1,0.0,1,2,0.0,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,None,googleadwords_int,Instal - first open,NaN,NaN,NaN,37,NaN,169,26,0.7027,0.0,NaN,NaN,0.0,NaN,12,12,0.0,23,93,0.0,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,11,28,0.0,NaN,NaN,NaN,NaN,NaN,NaN,11,28,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,None,googleadwords_int,Instal - first open,NaN,NaN,NaN,1922,NaN,8012,1254,0.6524,0.0,NaN,NaN,0.0,NaN,791,819,0.0,1323,4522,0.0,NaN,NaN,NaN,...,0.0,47.0,53.0,0.0,NaN,NaN,NaN,699,1449,0.0,NaN,NaN,NaN,NaN,NaN,NaN,743,1718,0.0,NaN,NaN,NaN,NaN,NaN,NaN
0,None,Facebook Ads,NaN,NaN,NaN,NaN,1,NaN,5,1,1.0000,0.0,NaN,NaN,0.0,NaN,1,1,0.0,1,4,0.0,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1,3,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1,3,0.0,Установки/1908,2.385125e+16,Установки / Google Play / Деньги/ Advantage+,2.385139e+16,N-Вам одобрен микрокредит,2.385195e+16

Заменяем пробелы в колонках

In [9]:
df_agre['Media Source (pid)'] = df_agre['Media Source (pid)'].str.replace(' ','_')

Группируем компании в единные источники

In [10]:
dfx = df_agre.groupby('Media Source (pid)').sum(numeric_only=True)
dfx

,Impressions,Clicks,CTR,Installs,Conversion Rate,Sessions,Loyal Users,Loyal Users/Installs,Total Revenue,Total Cost,ROI,ARPU,Average eCPI,af_complete_registration (Unique users),af_complete_registration (Event counter),af_complete_registration (Sales in USD),af_login (Unique users),af_login (Event counter),af_login (Sales in USD),contract_signed (Unique users),contract_signed (Event counter),contract_signed (Sales in USD),contract_signed_new (Unique users),contract_signed_new (Event counter),contract_signed_new (Sales in USD),...,first_open_new (Sales in USD),install_kreditomat (Unique users),install_kreditomat (Event counter),install_kreditomat (Sales in USD),loan_accepted (Unique users),loan_accepted (Event counter),loan_accepted (Sales in USD),loan_accepted_new (Unique users),loan_accepted_new (Event counter),loan_accepted_new (Sales in USD),loan_rejected (Unique users),loan_rejected (Event counter),loan_rejected (Sales in USD),loan_request (Unique users),loan_request (Event counter),loan_request (Sales in USD),loan_request_new (Unique users),loan_request_new (Event counter),loan_request_new (Sales in USD),submit_loan_application (Unique users),submit_loan_application (Event counter),submit_loan_application (Sales in USD),Campaign Id,Adset Id,Adgroup Id
Media Source (pid),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Facebook_Ads,0.0,0.0,0.0,1,0.0,5,1,1.0000,0.0,0.0,0.0,0.0,0.0,1,1,0.0,1,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,3,0.0,2.385125e+16,2.385139e+16,2.385195e+16
Organic,0.0,0.0,0.0,4595,0.0,0,3764,0.8192,0.0,0.0,0.0,0.0,0.0,2252,2689,0.0,4186,33439,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,4348,7991,0.0,418.0,827.0,0.0,0.0,2.0,0.0,2440,10757,0.0,0.0,3.0,0.0,0.0,3.0,0.0,2868,13627,0.0,0.000000e+00,0.000000e+00,0.000000e+00
googleadwords_int,0.0,0.0,0.0,1967,0.0,8218,1287,4.1551,0.0,0.0,0.0,0.0,0.0,808,836,0.0,1352,4636,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1570,1711,0.0,47.0,53.0,0.0,0.0,0.0,0.0,713,1486,0.0,0.0,0.0,0.0,0.0,0.0,0.0,757,1755,0.0,0.000000e+00,0.000000e+00,0.000000e+00

Удаляем лишние колонки

In [11]:
df = dfx.copy()



''' удаляем лишние колонки '''

df = df.drop([
             'Impressions',
             'CTR',
             'Conversion Rate',
             'Total Revenue',
             'Total Cost',
             'af_login (Unique users)',
             'loan_accepted (Unique users)',
             'install_kreditomat (Event counter)',
             'ROI',
             'ARPU',
             'Loyal Users',
             'Loyal Users/Installs',
             'loan_rejected (Unique users)',
             'Average eCPI',
             'install_kreditomat (Unique users)',
             'af_complete_registration (Unique users)',
             'submit_loan_application (Unique users)',
             'af_complete_registration (Sales in USD)',
             'af_login (Sales in USD)',
             'install_kreditomat (Sales in USD)',
             'loan_accepted (Sales in USD)',
             'loan_rejected (Sales in USD)',
             'submit_loan_application (Sales in USD)'], axis=1)

# # transposition columns
# df = df[['Media Source (pid)', 'Campaign (c)', 'Budget', 'Sessions', 'install_kreditomat (Event counter)', 'af_login (Event counter)', 'submit_loan_application (Event counter)', 'loan_rejected (Event counter)', 'loan_accepted (Event counter)']]
# df

# transposition columns without BUDGET
df = df[['Sessions', 'Installs', 'af_login (Event counter)', 'submit_loan_application (Event counter)', 'loan_rejected (Event counter)', 'loan_accepted (Event counter)']]
df

,Sessions,Installs,af_login (Event counter),submit_loan_application (Event counter),loan_rejected (Event counter),loan_accepted (Event counter)
Media Source (pid),,,,,,
Facebook_Ads,5,1,4,3,3,0.0
Organic,0,4595,33439,13627,10757,827.0
googleadwords_int,8218,1967,4636,1755,1486,53.0

Считаем конверсии

In [12]:



df

,Sessions,Installs,af_login (Event counter),submit_loan_application (Event counter),loan_rejected (Event counter),loan_accepted (Event counter)
Media Source (pid),,,,,,
Facebook_Ads,5,1,4,3,3,0.0
Organic,0,4595,33439,13627,10757,827.0
googleadwords_int,8218,1967,4636,1755,1486,53.0

Добавляем данные в таблицу по бюджету, просмотрам и кликам

In [13]:
''' add budgets, views, clicks '''
 
df_bvc = pd.DataFrame(index=['Budget', 'Views', 'Clicks'])

for i in range(len(bvc)): 
    df_bvc.insert(0, f"{retrieve_name(bvc[i])}", bvc[i], True)


df_bvc = df_bvc.T

df_bvc

                   Budget   Views  Clicks
Facebook_Ads          100    6000    1000
googleadwords_int    1680  646000   14500
Organic                 0       0       0

Объединение таблиц с бюджетом и с appsflyer

In [14]:
''' объединяюю таблицы '''

df = pd.concat([df_bvc, df], axis=1, join="inner")

Сортируем по колонке 'Installs'

In [15]:
''' сортирую по установкам '''

df = df.sort_values(by='Installs', ascending=False)
df

,Budget,Views,Clicks,Sessions,Installs,af_login (Event counter),submit_loan_application (Event counter),loan_rejected (Event counter),loan_accepted (Event counter)
Organic,0,0,0,0,4595,33439,13627,10757,827.0
googleadwords_int,1680,646000,14500,8218,1967,4636,1755,1486,53.0
Facebook_Ads,100,6000,1000,5,1,4,3,3,0.0

Считаем финанансовые метрики

In [17]:
def trunc(values, decs=0):
    return np.trunc(values * 10 ** decs) / (10 ** decs)
''' AMOUNT PERCENT '''

# получаем Clicks_to_Installs
cti = df[['Installs']].to_numpy() / (df[['Clicks']].to_numpy() / 100)
cti = trunc(cti, decs=1)
df.insert(4, "Clicks_to_Installs %", cti, True)


''' FINANCIAL '''

# получаем CPAp
cpap = df[['Budget']].to_numpy() / df[['loan_accepted (Event counter)']].to_numpy()
cpap = trunc(cpap, decs=2)
df.insert(3, "CPAp", cpap, True)

# получаем CPSu
cpsu = trunc(df[['Budget']].to_numpy() / df[['submit_loan_application (Event counter)']].to_numpy(), decs=2)
df.insert(3, "CPSu", cpsu, True)

# получаем CPI
cpi = trunc(df[['Budget']].to_numpy() / df[['Installs']].to_numpy(), decs=2)
df.insert(3, "CPI", cpi, True)

# получаем CPC
cpc = trunc(df[['Budget']].to_numpy() / df[['Clicks']].to_numpy(), decs=2)
df.insert(3, "CPC", cpc, True)

Меняем несущствующие значения на ноль

In [ ]:
df = df.replace([-np.inf, np.inf], [0, 0])
df.fillna(0,  inplace=True)
df

Делаем расстановку колонок в удобном порядке

In [ ]:
df = df[['Budget',
                'Views', 
                'Clicks', 
                'CPC',
                'Clicks_to_Installs %',
                'Installs',
               'CPI',
               'Installs_to_Login %',
               'af_login (Event counter)',
               'Installs_to_Submit %',
               'submit_loan_application (Event counter)',
               'CPSu',
               'Submit_to_Rejected %',
               'loan_rejected (Event counter)',
               'Submit_to_Accepted %',
               'loan_accepted (Event counter)',
               'CPAp',
               'Submit_to_Lost %'
                   ]]

Получаем курс Тенге и копируем таблицу с финансовыми метриками

In [ ]:
''' add USD to KZT cotverter '''

rates = Rates()

KZTUSD = rates.get_exchange_rate("USD", from_kzt=True)

# create copy of table with KZT 
df_kzt = df.copy()
financial_metrics = ['Budget', 'CPC', 'CPI', 'CPSu', 'CPAp']
df_kzt[financial_metrics] = df_kzt[financial_metrics] * KZTUSD
df_kzt

Создаем визуализацию таблицы

In [ ]:

plt.bar(df_kzt.index[[0, 1]], df_kzt.iloc[list(df_kzt['Budget'] > 0)].Budget.values)
plt.title('Budget')

In [ ]:
plt.subplot(2, 1, 1)
plt.bar(df_kzt.index[[0, 1]], df_kzt.iloc[list(df_kzt['CPC'] > 0)].CPC.values)
plt.title('CPC')

plt.subplot(2, 1, 2)
plt.bar(df_kzt.index[[0, 1]], df_kzt.iloc[list(df_kzt['CPI'] > 0)].CPI.values)
plt.title('CPI')

In [ ]:
plt.subplot(2, 1, 1)
plt.bar(df_kzt.index[[0, 1]], df_kzt.iloc[list(df_kzt['CPSu'] > 0)].CPSu.values)
plt.title('CPSu')

plt.subplot(2, 1,2)
plt.bar(df_kzt.index[[0, 1]], df_kzt.iloc[list(df_kzt['CPAp'] > 0)].CPAp.values)
plt.title('CPAp')

In [ ]:
 df_kzt.iloc[list(df_kzt['CPSu'] > 0)].CPSu.values